#version
version: "1.0"

permalink: /:year/:month/:day/:title/

# 站点设置
title: "bhtj27"
email: 2283740020@qq.com
description: "bhtj27的个人博客"
keywords: "bhtj27"

# 用户信息设置
weibo_username: bhtj27
github_username: bhtj27

# Markdown设置
kramdown:
  input:  GFM
  use_coderay: true
  coderay:
    coderay_line_numbers:  nil



# 地址设置
baseurl: "/bhtj27.github.io"
url: "http://127.0.0.1:4000"


# 分页设置
paginate: 10
paginate_path: "page/:num"

#scss设置
sass:
    sass_dir: /assets/stylesheet
    style: :compressed

# duoshuo设置
# duoshuo_shortname: 

# 百度统计设置
# baidu_analysis:
